FROM node:20-alpine AS base


FROM base as deps
WORKDIR /app

COPY package*.json ./

RUN npm ci


FROM base as developement

WORKDIR /app 

COPY  --from=deps app/node_modules ./

COPY ./prisma ./

RUN npx prisma generate

COPY . .

EXPOSE 3000

CMD [ "npm","run","dev" ]

FROM base as buider

WORKDIR /app

COPY --from=developement /app/node_modules ./

RUN npm run build




